name: tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python: ['3.9', '3.10', '3.11', '3.12', '3.13']

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up target Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Install nox
        run: |
            pip install nox
            nox --version

      - name: Run tests
        run: nox -s test-${{ matrix.python }}

      - name: Send coverage report
        uses: codecov/codecov-action@v1
        env:
          PYTHON: ${{ matrix.python }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          env_vars: PYTHON
